definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  models.Autor:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      nome:
        type: string
      sobrenome:
        type: string
      updatedAt:
        type: string
    type: object
  models.Editora:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      localidade:
        type: string
      nome:
        type: string
      updatedAt:
        type: string
    type: object
  models.Genero:
    properties:
      createdAt:
        type: string
      descricao:
        type: string
      id:
        type: integer
      updatedAt:
        type: string
    type: object
  schemas.AutorInput:
    properties:
      nome:
        type: string
      sobrenome:
        type: string
    type: object
  schemas.EditoraInput:
    properties:
      localidade:
        type: string
      nome:
        type: string
    type: object
  schemas.GeneroInput:
    properties:
      descricao:
        type: string
    type: object
info:
  contact: {}
paths:
  /autores/:
    get:
      consumes:
      - application/json
      description: Recupera a lista de autores
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Autor'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Lista autores
      tags:
      - autores
    post:
      consumes:
      - application/json
      description: Cria um novo autor
      parameters:
      - description: Dados do autor
        in: body
        name: autor
        required: true
        schema:
          $ref: '#/definitions/schemas.AutorInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Autor'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Cria autor
      tags:
      - autores
  /autores/{id}:
    delete:
      consumes:
      - application/json
      description: Remove o cadastro de um autor
      parameters:
      - description: ID do autor
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Deleta autor
      tags:
      - autores
    get:
      consumes:
      - application/json
      description: Recupera um autor por id
      parameters:
      - description: ID do autor
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Autor'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Recupera autor
      tags:
      - autores
    put:
      consumes:
      - application/json
      description: Atualiza os dados de um autor
      parameters:
      - description: ID do autor
        in: path
        name: id
        required: true
        type: integer
      - description: Dados do autor
        in: body
        name: autor
        required: true
        schema:
          $ref: '#/definitions/schemas.AutorInput'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Atualiza autor
      tags:
      - autores
  /editoras/:
    get:
      consumes:
      - application/json
      description: Recupera a lista de editoras
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Editora'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Lista editoras
      tags:
      - editoras
    post:
      consumes:
      - application/json
      description: Cria uma nova editora
      parameters:
      - description: Dados da editora
        in: body
        name: editora
        required: true
        schema:
          $ref: '#/definitions/schemas.EditoraInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Editora'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Cria editora
      tags:
      - editoras
  /editoras/{id}:
    delete:
      consumes:
      - application/json
      description: Remove o cadastro de uma editora
      parameters:
      - description: ID da editora
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Deleta editora
      tags:
      - editoras
    get:
      consumes:
      - application/json
      description: Recupera uma editora por id
      parameters:
      - description: ID da editora
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Editora'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Recupera editora
      tags:
      - editoras
    put:
      consumes:
      - application/json
      description: Atualiza os dados de uma editora
      parameters:
      - description: ID da editora
        in: path
        name: id
        required: true
        type: integer
      - description: Dados da editora
        in: body
        name: editora
        required: true
        schema:
          $ref: '#/definitions/schemas.EditoraInput'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Atualiza editora
      tags:
      - editoras
  /generos/:
    get:
      consumes:
      - application/json
      description: Recupera a lista de generos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Genero'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Lista generos
      tags:
      - generos
    post:
      consumes:
      - application/json
      description: Cria um novo genero
      parameters:
      - description: Dados do genero
        in: body
        name: genero
        required: true
        schema:
          $ref: '#/definitions/schemas.GeneroInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Genero'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Cria genero
      tags:
      - generos
  /generos/{id}:
    delete:
      consumes:
      - application/json
      description: Remove o cadastro de um genero
      parameters:
      - description: ID do genero
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Deleta genero
      tags:
      - generos
    get:
      consumes:
      - application/json
      description: Recupera um genero por id
      parameters:
      - description: ID do genero
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Genero'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Recupera genero
      tags:
      - generos
    put:
      consumes:
      - application/json
      description: Atualiza os dados de um genero
      parameters:
      - description: ID do genero
        in: path
        name: id
        required: true
        type: integer
      - description: Dados do genero
        in: body
        name: genero
        required: true
        schema:
          $ref: '#/definitions/schemas.GeneroInput'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Atualiza genero
      tags:
      - generos
swagger: "2.0"
